name: setup-node
description: 'Setup Node.js âš™ï¸ - Cache dependencies âš¡ - Install dependencies ğŸ”§'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js âš™ï¸
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'

    - name: Cache Cypress binary âš¡
      id: cache_cypress
      uses: actions/cache@v4
      with:
        path: ~/.cache/Cypress
        key: cypress-cache-${{ runner.os }}-${{ hashFiles('package.json') }}

    - name: Cache dependencies âš¡
      id: cache_dependencies
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node-modules-${{ runner.os }}-${{ hashFiles('package.json') }}

    # - name: Remove npm cache
    #   shell: bash
    #   run: npm cache clean --force

    - name: Install pnpm
      shell: bash
      run: npm install -g pnpm

    - name: Install dependencies ğŸ”§ (without package-lock)
      shell: bash
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: pnpm install --no-lockfile

    - name: Verify Cypress installation âœ…
      shell: bash
      run: npx cypress install
